name: Publish package to the Maven Central Repository
# The job will be triggered when a release is created
on:
  release:
    types: [created]
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: Publish to the Maven Central Repository
        run: ./gradlew clean --info --stacktrace -PsigningKey='${{ secrets.GPG_SIGNING_KEY }}' -PsigningPassword='${{ secrets.GPG_SIGNING_PASSWORD }}' publish
        env:
          OSSRH_USER_TOKEN_USERNAME: ${{ secrets.OSSRH_USER_TOKEN_USERNAME }}
          OSSRH_USER_TOKEN_PASSWORD: ${{ secrets.OSSRH_USER_TOKEN_PASSWORD }}
      - name: Wait before notification
        run: |
          echo "Waiting 60 seconds for the repository to be indexed by Sonatype..."
          sleep 60
      - name: Notify Central of Upload (Manual Staging Promotion)
        run: |
          echo "Querying for open staging repository..."
          RESPONSE=$(curl -s -u "${{ secrets.OSSRH_USER_TOKEN_USERNAME }}:${{ secrets.OSSRH_USER_TOKEN_PASSWORD }}" \
            "https://ossrh-staging-api.central.sonatype.com/manual/search/repositories?ip=any&profile_id=com.cjbooms")
          
          REPO_KEY=$(echo "$RESPONSE" | jq -r '.repositories[] | select(.state == "open") | .key')

          if [[ "$REPO_KEY" == "null" ]]; then
            echo "No open repository found"
            exit 1
          fi

          echo "Notifying Sonatype to register repository in Central Publisher Portal..."
          curl -X POST -H "Accept: application/json" \
            -u "${{ secrets.OSSRH_USER_TOKEN_USERNAME }}:${{ secrets.OSSRH_USER_TOKEN_PASSWORD }}" \
            "https://ossrh-staging-api.central.sonatype.com/manual/upload/repository/$REPO_KEY"
