name: Publish package to the Maven Central Repository
# The job will be triggered when a release is created
on:
  release:
    types: [created]
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: Publish to the Maven Central Repository
        run: ./gradlew clean --stacktrace -PsigningKey='${{ secrets.GPG_SIGNING_KEY }}' -PsigningPassword='${{ secrets.GPG_SIGNING_PASSWORD }}' publish
        env:
          OSSRH_USER_TOKEN_USERNAME: ${{ secrets.OSSRH_USER_TOKEN_USERNAME }}
          OSSRH_USER_TOKEN_PASSWORD: ${{ secrets.OSSRH_USER_TOKEN_PASSWORD }}
      - name: Finalise upload so it appears in Central Portal
        run: |
          curl -X POST \
            -H "Accept: application/json" \
            -u "${{ secrets.OSSRH_USER_TOKEN_USERNAME }}:${{ secrets.OSSRH_USER_TOKEN_PASSWORD }}" \
            "https://central.sonatype.com/api/v1/publisher/manual/upload/defaultRepository/com/cjbooms"

